---
title: "Step-by-step instruction"
output:
  html_document:
    fig_cap: yes
    highlight: tango
    smooth_scroll: no
    theme: flatly
    toc: yes
    toc_float: yes
---

On this page you can find a brief step-by-step instruction on how to collect data according to the TALD methodology.

-----------

## Step 1 - Create a folder

* Make a folder for your feature in the [features' folder](https://drive.google.com/drive/u/2/folders/1Rrm0NOH2E7dGMC97TdCFhjg7Y_FrAU3i).

-----------

## Step 2 - Add data

* Copy the [feature template](https://docs.google.com/spreadsheets/d/1HCoEBiz8A2Vd9LUApRLtMANpnsUJN-k6EaXrBYfN0IU/edit?gid=0#gid=0) in the folder.
 
* Collect data for each language from descriptive literature, which you can find in [our library](https://drive.google.com/drive/u/2/folders/14RBA31Cj1MsFSiV4E_ZqTLGOhI1dUfMD). Fill in all required columns (see [List of columns](datasets.html#list-of-columns) for an explanation of the column names).

See [Datasets](datasets.html) for more detailed guidelines.
 
-----------

## Step 3 - Write a chapter

* Write an introductory chapter about your feature in google docs and upload it to your feature’s folder.

* Contact your expert consultant and the responsible editor and ask them to read your chapter.

* After the final version of the chapter is ready, convert it to rmarkdown using our [chapter template](chapter_template/chapter_template.Rmd) and the [cheat sheet](chapter_template/chapter_cheatsheet.Rmd).

* Compile your own list of references using this [table template](https://docs.google.com/spreadsheets/d/1DrNPxHFnCHaUAdFgPzdAhXMJ4nEzl0MvZsTcvcA03EY/edit?gid=0#gid=0). 

See [Chapters](chapters.html) for more detailed guidelines.

------------

## Step 4 - Check your files

* Check that by the end of the work, your folder in the [Atlas drive](https://drive.google.com/drive/u/2/folders/1Rrm0NOH2E7dGMC97TdCFhjg7Y_FrAU3i) contains the following things:

  + your feature table, with the name of your feature in lower case as filename: `YOUR_FEATURE`
  + your chapter text in `.Rmd` format (in addition to a draft version in `.doc` format), with the name of your feature in lower case as filename: `YOUR_FEATURE.Rmd`
  + a table with the references used in your text, with the name of your feature in lower case as filename: `YOUR_FEATURE_bib`
  
* **Make sure the filenames of your feature table, text, and references are the same**, e.g. `evidentialty_tense` (data), `evidentiality_tense.Rmd` (text), `evidentiality_tense_bib` (chapter references) 

* **Don't forget** to add the date on which you submit your finished work to us in the **date** column of your feature table!

------------

## Step 5 (Optional) - Changes after publication

What to do if you want to make changes to your data or chapter after it has been published?

* Create an issue on the [TALD Github](https://github.com/LingConLab/TALD/issues) where you outline the proposed changes.

* Please mention the title of your chapter in the subject line, and indicate whether you are the author (other users can also propose changes, and we might not be able to recognize you from your Github username).

* You will be contacted by an editor to discuss how to proceed. The process will differ depending on what and how much you want to change.

* You can also contact the Atlas team (cauatlas@gmail.com) or your responsible editor directly.




